services:
  cds:
    container_name: "CDS"
    depends_on:
      db:
        condition: service_started
      localstack:
        condition: service_healthy
    image: cds.api
    build:
      context: .
      dockerfile: CDS.API/Dockerfile
    environment:
      - "ConnectionStrings__Postgres=Host=10.0.2.21:5432;Database=cds;Username=cds;Password=cds"
    ports:
      - "8080:8080"
    dns:
      - 10.0.2.20
    networks:
      - ls

  mock.asset:
    container_name: "mock.asset"
    image: mock.asset
    build:
      context: .
      dockerfile: Mock.Asset/Dockerfile
    ports:
      - "8081:8080"
    dns:
      - 10.0.2.20
    networks:
      - ls

  mock.order:
    container_name: "mock.order"
    image: mock.order
    build:
      context: .
      dockerfile: Mock.Order/Dockerfile
    ports:
      - "8082:8080"
    dns:
      - 10.0.2.20
    networks:
      - ls

  mock.briefing:
    container_name: "mock.briefing"
    image: mock.briefing
    build:
      context: .
      dockerfile: Mock.Briefing/Dockerfile
    ports:
      - "8083:8080"
    networks:
      ls:
        ipv4_address: 10.0.2.22

  mock.content.distribution:
    container_name: "mock.content.distribution"
    image: mock.content.distribution
    build:
      context: .
      dockerfile: Mock.Content.Distribution/Dockerfile
    ports:
      - "8084:8080"
    dns:
      - 10.0.2.20
    networks:
      - ls
  
  localstack:
    container_name: "CDS.localstack"
    image: localstack/localstack
    ports:
      - "127.0.0.1:4566:4566"
      - "127.0.0.1:4510-4559:4510-4559"
    environment:
      - DEBUG=${DEBUG:-0}
    volumes:
      - "${LOCALSTACK_VOLUME_DIR:-./volume}:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "./bootstrap/localstack:/etc/localstack/init/ready.d"
    networks:
      ls:
        ipv4_address: 10.0.2.20
        
  db:
    container_name: "CDS.db"
    image: postgres:alpine
    restart: always
    environment:
      - POSTGRES_DB=cds
      - POSTGRES_USER=cds
      - POSTGRES_PASSWORD=cds
    ports:
      - '5432:5432'
    volumes:
      - "cds-db:/var/lib/postgresql/data"
    networks:
      ls:
        ipv4_address: 10.0.2.21

networks:
  ls:
    ipam:
      config:
        - subnet: 10.0.2.0/24
          
volumes:
  cds-db:
    driver: local