services:
  cds.api:
    image: cds.api
    build:
      context: .
      dockerfile: CDS.API/Dockerfile
    ports:
      - "8080:8080"

  mock.asset:
    image: mock.asset
    build:
      context: .
      dockerfile: Mock.Asset/Dockerfile
    ports:
      - "8081:8080"