services:
  cds.api:
    image: cds.api
    build:
      context: .
      dockerfile: CDS.API/Dockerfile
    ports:
      - "8080:8080"
    dns:
      - 10.0.2.20
    networks:
      - ls

  mock.asset:
    image: mock.asset
    build:
      context: .
      dockerfile: Mock.Asset/Dockerfile
    ports:
      - "8081:8080"
    dns:
      - 10.0.2.20
    networks:
      - ls

  mock.order:
    image: mock.order
    build:
      context: .
      dockerfile: Mock.Order/Dockerfile
    ports:
      - "8082:8080"
    dns:
      - 10.0.2.20
    networks:
      - ls

  mock.briefing:
    image: mock.briefing
    build:
      context: .
      dockerfile: Mock.Briefing/Dockerfile
    ports:
      - "8083:8080"

  mock.content.distribution:
    image: mock.content.distribution
    build:
      context: .
      dockerfile: Mock.Content.Distribution/Dockerfile
    ports:
      - "8084:8080"
    dns:
      - 10.0.2.20
    networks:
      - ls
  
  localstack:
    container_name: "cds-localstack-docker"
    image: localstack/localstack
    ports:
      - "127.0.0.1:4566:4566"
      - "127.0.0.1:4510-4559:4510-4559"
    environment:
      - DEBUG=${DEBUG:-0}
    volumes:
      - "${LOCALSTACK_VOLUME_DIR:-./volume}:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "./bootstrap/localstack:/etc/localstack/init/ready.d"
    networks:
      ls:
        ipv4_address: 10.0.2.20
        
  db:
    image: postgres:alpine
    restart: always
    environment:
      - POSTGRES_DB=cds
      - POSTGRES_USER=cds
      - POSTGRES_PASSWORD=cds
    ports:
      - '5432:5432'
    volumes:
      - "./db-data:/var/lib/postgresql/data"

networks:
  ls:
    ipam:
      config:
        - subnet: 10.0.2.0/24